version: "3.3"

services:
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/appuser/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:13
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  # wait:
  #   image: dokku/wait
volumes:
  database-data: {}
