# Generated by Django 3.1.6 on 2021-05-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameAnalytics', '0002_auto_20210502_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
