# Generated by Django 3.1.6 on 2021-05-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameAnalytics', '0003_auto_20210506_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
