# Generated by Django 3.1.6 on 2021-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameAnalytics', '0004_auto_20210506_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
